all: Library.class Person.class Staff.class Users.class Screen.class Main.class


Library.class: Library.java
	javac Library.java


Person.class: Person.java
	javac Person.java


Staff.class: Staff.java
	javac Staff.java



Users.class: Users.java
	javac Users.java


Screen.class: Screen.java
	javac Screen.java


Main.class: Main.java
	javac Main.java

run:
	java Main

clean:
	rm -f *.class
